name: CD docker image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
    env:
      PYTHON: ${{ matrix.python }}
    steps:
      uses: docker/build-push-action@v1
      names: push hello-submarine to dockerhub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: pingsutw/hello-submarine
        tags: latest