name: CD docker image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
    env:
      PYTHON: ${{ matrix.python }}
    steps: # https://github.com/docker/build-push-action/blob/master/.github/workflows/main.yml
      - name: Check out code
        uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        name: Build & push Docker image - hello-submarine
        with:
          repository: pingsutw/hello-submarine
          tags: latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}